
import {Lato} from 'next/font/google'


const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'Social Tree',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>
        
          <div >
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
